### ISSUE TITLE
Copy coordinates to clipboard

### ISSUE THREAD

**Issue by P3run** [bellingcat/avoc#9]
Another idea - button/icon to copy the current coordinates to the clipboard (format: lat,lng - e.g. 51.50822812995682,-0.07613299233414361).

**Comment by haruspeks** [comment]
Nice one, I can see its usefulness when a user has to copy-paste coords and paste them into another tool.

I wonder if there are other quick action buttons that might be added as well? Open question.

**Comment by P3run** [comment]
Yeah, paste to another tool or... report/notes :).

That's the only "quick action" that came to my mind but your tool has great potential :).

**Comment by haruspeks** [comment]
Done, clipboard button has been added.

**Comment by P3run** [comment]
Works great! Thanks!
